# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 525)
        MainWindow.setMinimumSize(QtCore.QSize(600, 525))
        MainWindow.setMaximumSize(QtCore.QSize(600, 525))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(600, 500))
        self.frame.setMaximumSize(QtCore.QSize(600, 500))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.483, y1:0, x2:0.472637, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(0, 40, 62, 255));\n"
"border-radius:20px;\n"
"border:1px solid #00007f;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 50, 491, 71))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 25pt \"Arial\";\n"
"border:None")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(240, 130, 131, 31))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 15pt \"Arial\";\n"
"border:None")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(240, 230, 131, 31))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 15pt \"Arial\";\n"
"border:None;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.users = QtWidgets.QLineEdit(self.frame)
        self.users.setGeometry(QtCore.QRect(170, 160, 261, 31))
        self.users.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border:None")
        self.users.setAlignment(QtCore.Qt.AlignCenter)
        self.users.setObjectName("users")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(170, 260, 261, 31))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border:None")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.bt_ingresar = QtWidgets.QPushButton(self.frame)
        self.bt_ingresar.setGeometry(QtCore.QRect(230, 340, 151, 41))
        self.bt_ingresar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}")
        self.bt_ingresar.setObjectName("bt_ingresar")
        self.salir = QtWidgets.QPushButton(self.frame)
        self.salir.setGeometry(QtCore.QRect(260, 440, 101, 41))
        self.salir.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border:None;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}")
        self.salir.setObjectName("salir")
        self.usuario_incorrecto = QtWidgets.QLabel(self.frame)
        self.usuario_incorrecto.setGeometry(QtCore.QRect(220, 190, 161, 31))
        self.usuario_incorrecto.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:None;")
        self.usuario_incorrecto.setText("")
        self.usuario_incorrecto.setAlignment(QtCore.Qt.AlignCenter)
        self.usuario_incorrecto.setObjectName("usuario_incorrecto")
        self.contrasena_incorrecta = QtWidgets.QLabel(self.frame)
        self.contrasena_incorrecta.setGeometry(QtCore.QRect(210, 290, 191, 31))
        self.contrasena_incorrecta.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:None;")
        self.contrasena_incorrecta.setText("")
        self.contrasena_incorrecta.setAlignment(QtCore.Qt.AlignCenter)
        self.contrasena_incorrecta.setObjectName("contrasena_incorrecta")
        self.cargando = QtWidgets.QLabel(self.frame)
        self.cargando.setGeometry(QtCore.QRect(240, 380, 131, 31))
        self.cargando.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:None;")
        self.cargando.setText("")
        self.cargando.setAlignment(QtCore.Qt.AlignCenter)
        self.cargando.setObjectName("cargando")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.salir.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Detector Aviones Militares"))
        self.label_2.setText(_translate("MainWindow", "Usuario"))
        self.label_3.setText(_translate("MainWindow", "Contraseña"))
        self.users.setPlaceholderText(_translate("MainWindow", "Ingrese su usuario"))
        self.password.setPlaceholderText(_translate("MainWindow", "Ingrese su contraseña"))
        self.bt_ingresar.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.salir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
