# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vista1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vista1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 625)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 625))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1000, 600))
        self.frame.setMaximumSize(QtCore.QSize(1000, 600))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.483, y1:0, x2:0.472637, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(0, 40, 62, 255));\n"
"border-radius:25px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(360, 20, 251, 41))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 25pt \"Arial\";\n"
"border:None")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.nueva_prediccion = QtWidgets.QPushButton(self.frame)
        self.nueva_prediccion.setGeometry(QtCore.QRect(40, 510, 161, 51))
        self.nueva_prediccion.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}")
        self.nueva_prediccion.setObjectName("nueva_prediccion")
        self.nueva_prediccion_2 = QtWidgets.QPushButton(self.frame)
        self.nueva_prediccion_2.setGeometry(QtCore.QRect(810, 510, 161, 51))
        self.nueva_prediccion_2.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    border:None;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\"\n"
"}")
        self.nueva_prediccion_2.setObjectName("nueva_prediccion_2")
        self.tabla_predicciones = QtWidgets.QTableWidget(self.frame)
        self.tabla_predicciones.setGeometry(QtCore.QRect(15, 81, 491, 411))
        self.tabla_predicciones.setStyleSheet("")
        self.tabla_predicciones.setObjectName("tabla_predicciones")
        self.tabla_predicciones.setColumnCount(0)
        self.tabla_predicciones.setRowCount(0)
        self.mostrar_imagen = QtWidgets.QLabel(self.frame)
        self.mostrar_imagen.setGeometry(QtCore.QRect(524, 85, 461, 401))
        self.mostrar_imagen.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 25pt \"Arial\";\n"
"border:None")
        self.mostrar_imagen.setText("")
        self.mostrar_imagen.setObjectName("mostrar_imagen")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.nueva_prediccion_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Predicciones"))
        self.nueva_prediccion.setText(_translate("MainWindow", "Nueva Predicción"))
        self.nueva_prediccion_2.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
